name: Print Github Secrets

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Secrets
        run: |
          echo "MY_SECRET_1: ${{ secrets.MY_SECRET_1 }}"
          echo "MY_SECRET_2: ${{ secrets.MY_SECRET_2 }}"